### ISSUE TITLE
OrdinaryDiffEq >= 6.85 Compatibility issue

### ISSUE THREAD

**Issue by SamBoutin** [mikelehu/IRK.jl#66]
As discussed in https://github.com/SciML/IRKGaussLegendre.jl/issues/1#issuecomment-623862578 the `IRKGL16`  solver currently subtype `OrdinaryDiffEqAlgorithm`.

As of `OrdinaryDiffEq` 6.85, this type (`OrdinaryDiffEqAlgorithm`) is no longer exported by default, which breaks compilation of `IRKGaussLegendre.jl`. 

I am not familiar enough with the inner workings of either packages to know if other breaking changes were introduced in v"6.85", but I believe a short-term fix would be to explicitly import the `OrdinaryDiffEqAlgorithm` subtype.

**Comment by mikelehu** [comment]
Thank you, Chris.

I wanted to take this opportunity to ask if you are interested in including our new integrator for few-body problems as a package in the SciML ecosystem. Otherwise, we would register it as a general Julia package.
I sent you an email during the conference, but I think it was the wrong address (if you prefer, you can contact me at mikel.antonan@ehu.eus)

**Comment by ChrisRackauckas** [comment]
Yes, I got the email. It took me awhile to look through the construction and it looks really nice. I like how the SIMD works (similar to a few codes we've written) and the estimators make sense. There's a few oddities with connecting to the common interface, but I could handle those pretty easily (there's `save_steps` for example instead of `msteps`, and the extrapolation choice should move to the alg, etc. to act more like the general interface). I'd be happy to help with getting that into a package and maintaining it, similar to this repo

**Comment by SamBoutin** [comment]
Thanks Chris and Mikel for quickly resolving the issue. Could one of you tag a new release (or other steps needed) to register this new version 0.2.8? Or point me to the steps needed to register it.
